on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * 1-5'
name: Workdays Morning
jobs:
  workdays-morning:
    runs-on: ubuntu-latest
    outputs:
      imageUrl: ${{ steps.loadimg.outputs.imageUrl }}
    env:
      ZENSERP_API_KEY: ${{ secrets.ZENSERP_API_KEY }}
    steps:
      - uses: actions/checkout@master
      - name: Install jq
        run: sudo apt-get install -y jq
      - name: Make script executable
        run: chmod +x ./scripts/random-google-image.sh
      - id: loadimg
        name: Fetch random google image
        run: ./scripts/random-google-image.sh
        shell: bash
      - name: Workdays Morning
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.WORKDAYS_ID }}
          webhook_token: ${{ secrets.WORKDAYS_TOKEN }}
          username: "Guten Morgen"
          avatar_url: "https://raw.githubusercontent.com/Devsome/discord-coding-notification/main/images/avatar.png"
          message: Ich wünsche euch allen ein wunderschönen Guten Morgen!
          file: ${{ env.IMAGEFILE }}
