on:
  workflow_dispatch:
#  schedule:
#    - cron: '0 8 * * 1-5'
name: Workdays Morning
jobs:
  workdays-morning:
    runs-on: ubuntu-latest
    outputs:
      imageUrl: ${{ steps.loadimg.outputs.imageUrl }}
    steps:
      - uses: actions/checkout@master
      - id: loadimg
        name: Fetch random google image
        run: ./scripts/random-google-image.sh
        shell: bash
      - name: Workdays Morning
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.WORKDAYS_ID }}
          webhook_token: ${{ secrets.WORKDAYS_TOKEN }}
          username: "Guten Morgen"
          avatar_url: "https://raw.githubusercontent.com/Devsome/discord-coding-notification/main/images/avatar.png"
          message: |
            Ich wünsche euch allen ein wunderschönen Guten Morgen!
            $ {{ steps.loadimg.outputs.imageUrl }}
