on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * 1-5'
name: Workdays Morning
jobs:
  workdays-morning:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Workdays Morning
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.WORKDAYS_ID }}
          webhook_token: ${{ secrets.WORKDAYS_TOKEN }}
          username: "Guten Morgen"
          avatar_url: "https://raw.githubusercontent.com/Devsome/discord-coding-notification/main/images/avatar.png"
          message: |
            Ich wünsche euch allen ein wunderschönen Guten Morgen!
            (Hier Tollas Ü40 Bild einfügen)
